@startuml
enum State {
    off,
    on,
    unknown
}
enum Connectivity {
    connected,
    offline
}
abstract class Smartphone {
}
interface IAppStore {
}
class ApplePhone {
}
abstract class AndroidPhone {
}
class SamsungPhone {
}

Smartphone o-- "PhoneState" State
Smartphone o-- "ConnectionState" Connectivity
Smartphone <|-- ApplePhone
IAppStore <|.. ApplePhone
Smartphone <|-- AndroidPhone
IAppStore <|.. AndroidPhone
AndroidPhone <|-- SamsungPhone
@enduml
